bbs/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('personal/',views.personal,name='personal'),
    path('confirm/',views.confirm,name='confirm'),
    path('prompt/',views.prompt,name='prompt'),
    path('login/', views.login_user, name="login_user"),
    path('logout/',views.logout_user, name='logout_user'),
    path('register/',views.register_user, name='register_user'),
    path('find_password/', views.find_password, name='find_password'),
    path('set_password/', views.set_password, name='set_password')
]

bbs/bbscopy/urls.py
from django.urls import path
from . import views

app_name = "bbscopy"
urlpatterns = [
    # path('', views.QuestionListView.as_view(), name='index'),
    path('', views.index, name='index'),
    # path('topic/', views.TopicCreateView.as_view(), name='topic'),
    path('topic/', views.topic, name='topic'),
    path('reply/<int:bbscopy_id>/', views.reply, name='reply'),
    path('detail/<int:bbscopy_id>/', views.detail, name='detail'),
]

bbs/up2u_bbs/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('bbscopy/', include('bbscopy.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

bbs/accounts/models.py
import os
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class ConfirmString(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    code = models.CharField(max_length=256)
    pub_date = models.DateField(auto_now_add=True)


def upload_to(instance,filename):
    now = timezone.now()
    base,ext = os.path.splitext(filename)
    ext = ext.lower()
    return f'users/{now:%Y/%m/%Y%m%d%H%M%S}{ext}'


class UserUpdate(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    sex = models.CharField(max_length=2,choices=((1,'男'),(2,'女')),default=1)
    country = models.CharField(max_length=20,default='中国')
    picture = models.FileField(blank=True,null=True,upload_to=upload_to)

bbs/accounts/forms.py
from django import forms
from django.contrib.auth.models import User

class RegisterForm(forms.ModelForm):
    username = forms.CharField(
        label='用户名',
        widget = forms.TextInput(
            attrs={
                'minlength':'3',
                'maxlength':'8',
                'class':'form-control',
                'placeholder':'请设置用户名...'
            }
        )
    )
    password1 = forms.CharField(
        label='密码',
        widget = forms.PasswordInput(
            attrs={
                'minlength':'6',
                'maxlength':'18',
                'class':'form-control',
                'placeholder':'请设置密码...'
            }
        )
    )
    password2 = forms.CharField(
        label='再次输入密码',
        widget = forms.PasswordInput(
            attrs={
                'minlength':'6',
                'maxlength':'18',
                'class':'form-control',
                'placeholder':'请确保您的两次输入密码一致...'
            }
        )
    )
    email = forms.CharField(
        label = '邮箱',
        widget = forms.EmailInput(
            attrs={
                'class':'form-control',
                'placeholder':'请设置你的邮箱...'
            }
        )
    )
    class Meta:
        model = User
        fields = ('username','password1','password2','email')

    # 全局钩子，判断两次输入是否相等
    def clean(self):
        if self.cleaned_data["password1"] == self.cleaned_data["password2"]:
            return self.cleaned_data

bbs/accounts/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from .forms import RegisterForm
from django.contrib.auth.models import User
from .models import UserUpdate
from bbscopy.models import Question
from bbscopy.models import Choice


import hashlib
from django.utils import timezone
from .models import ConfirmString
from django.conf import settings
from django.core.mail import EmailMultiAlternatives

from django.contrib.auth.decorators import login_required


# 个人中心
@login_required
def personal(request):
    
    # 判断是否发生更新信息的行为
    if request.method == 'POST':
        # 先获取到提交的数据集，还有文件
        data = request.POST
        pic  = request.FILES
        # 更改数据
        userupdate = get_object_or_404(UserUpdate,user_id=request.user.id)
        userupdate.sex = data['personal_sex']
        userupdate.country = data['personal_country']
        # 不上传头像，默认不操作
        try:
            userupdate.picture = pic['personal_picture']
        except:
            pass
        # 保存数据    
        userupdate.save()


    now_user_q_list = Question.objects.filter(user_id = request.user.id)
    now_user_c_list = Choice.objects.filter(user_id = request.user.id)

    # 将这个用户的所有回帖id与帖子来源对应起来
    c_to_d_dict = {}
    for c in now_user_c_list:
        # 从原帖对象里面寻找
        c_to_d_dict[c.id] = Question.objects.get(id=c.question_id).question_title

    now_user_d_object = get_object_or_404(UserUpdate, user_id=request.user.id)
    

    context = {
        'now_user':{'user':request.user,'is_login':request.user.is_authenticated},
        'now_user_q':now_user_q_list,
        'now_user_c':now_user_c_list,
        'now_user_d':now_user_d_object,
        'c_to_d_dict':c_to_d_dict,
    }
    
    return render(request,'accounts/personal.html',context)


# 登录
def login_user(request):

    # 发生登录行为的时候，激活这个if代码块
    if request.method == 'POST':
        # 获取POST发送的数据
        username = request.POST['inputName']
        password = request.POST['inputPassword']

        # 判断用户是否在auth_user数据表里 
        user = authenticate(username=username,password=password)
        # 进行登陆操作
        if user:
            # 判断是否经过邮箱验证
            if user.is_superuser:
                login(request,user)
                return HttpResponseRedirect(reverse('bbscopy:index'))
            else:
                error_message = '用户还未邮箱验证！'
                return render(request,'accounts/login.html',{'error_message':error_message})

        else:
            error_message = '用户名或密码错误！'
            return render(request,'accounts/login.html',{'error_message':error_message})

    return render(request,'accounts/login.html')


# 登出
@login_required
def logout_user(request):
    # 自动退出当前正在登陆的帐号
    logout(request)
    return HttpResponseRedirect(reverse('bbscopy:index'))


# 注册
def register_user(request):

    registerform = RegisterForm()

    # 发生注册行为的时候，激活这个if代码块
    if request.method == 'POST':
            form = RegisterForm(request.POST)
            if form.is_valid():
                user = form.save(commit=False)
                username = form.cleaned_data.get('username')
                password1 = form.cleaned_data.get('password1')
                password2 = form.cleaned_data.get('password2')
                email = form.cleaned_data.get('email')
                # 判断密码不一致
                if password1 != password2:
                    error_message = '两次输入的密码不同！'
                    return render(request, 'accounts/register.html', 
                    {'error_message':error_message,'registerform':registerform})
                else:
                     # 判断是否有重名
                    same_name_user = User.objects.filter(username=username)
                    if same_name_user:
                        error_message = '用户名已经存在！'
                        return render(request, 'accounts/register.html', 
                    {'error_message':error_message,'registerform':registerform})
                     # 判断是否有重复邮箱
                    same_email_user = User.objects.filter(email=email)
                    if same_email_user:
                        error_message = '该邮箱已经被注册了！'
                        return render(request, 'accounts/register.html', 
                    {'error_message':error_message,'registerform':registerform})

                # 加密的方式保存密码
                user.set_password(form.cleaned_data['password1'])
                user.save()

                # 外键UserUpdate也应当更新进去用户
                u = UserUpdate.objects.create(user_id=user.id)
                u.save()

                # 发送注册码，激活用户
                code = make_confirm_string(user)
                send_email_for_register(email, code)

                # 发送邮件成功以后，跳转到验证页面
                success_message = '邮箱已发送，请验证邮箱完成注册'
                return render(request,'accounts/prompt.html',{'success_message':success_message})

    return render(request,'accounts/register.html',{'registerform':registerform})


# 验证注册
@login_required
def confirm(request):
    code = request.GET.get('code', None)
    # 先判断url的code是否有效
    try:
        confirm = ConfirmString.objects.get(code=code)
    except:
        error_message = '无效的确认请求!'
        return render(request, 'accounts/confirm.html', {'error_message':error_message})
    
    # confirm一旦被获取到，修改权限，允许登录：
    confirm.user.is_superuser = 1
    confirm.user.save()
    # 用户已经拥有登录权限了,confirm留着没用了
    confirm.delete()
    success_message = '验证邮箱成功！将自动登录'
    return render(request, 'accounts/confirm.html', {'success_message':success_message})


# 跳转
@login_required
def prompt(request):
    return render(request,'accounts/prompt.html')


# 找回密码
def find_password(request):
    if request.method == 'POST':
        username = request.POST['inputName']
        email = request.POST['inputEmail']
        user_object = User.objects.filter(username=username,email=email).first()
        if not user_object:
            error_message = '用户名与邮箱不匹配！'
            return render(request, 'accounts/find_password.html',
            {'error_message':error_message})
        else:
            # 发送编码，找回密码
            code = make_password_string(user_object)
            send_email_for_find(email, code)
            # 发送邮件成功以后，跳转到验证页面
            success_message = '邮箱已发送，请验证邮箱完成校验'
            return render(request,'accounts/prompt.html',{'success_message':success_message})

    return render(request, 'accounts/find_password.html')


# 设置密码
def set_password(request):
    if request.method == 'GET':
        code = request.GET.get('code', None)
        try:
            confirm = ConfirmString.objects.get(code=code)
        except:
            error_message = '无效的确认请求!'
            return render(request, 'accounts/set_password.html',
            {'error_message':error_message, 'success_status':0})
        # 取出要找回密码的用户名字
        user_id = confirm.user_id
        username = User.objects.get(id=user_id).username
        success_message = '请设置你的新密码'
        return render(request, 'accounts/set_password.html',
            {'success_message':success_message, "username":username, 'success_status':0})

    # 提交新密码
    if request.method == 'POST':
        username = request.POST['inputName']
        password1 = request.POST['inputPassword1']
        password2 = request.POST['inputPassword2']
        if password1 != password2:
            error_message = '两次输入的密码不同！'
            return render(request, 'accounts/set_password.html', 
            {'error_message':error_message, "username":username, 'success_status':0})
        else:
            # 设置密码
            user = User.objects.get(username=username)
            user.set_password(password1)
            user.save()
            # 设置成功则删除编码
            confirm = ConfirmString.objects.get(user_id=user.id)
            confirm.delete()
            # 发送设置成功的状态码，跳转到登录界面
            success_message = '设置密码成功，自动跳转中……'
            return render(request, 'accounts/set_password.html', 
                {'success_message':success_message, 'success_status':1})


# 哈希混淆加盐
def hash_code(s, salt='Masterpaopao'):
    h = hashlib.sha256()
    s += salt
    h.update(s.encode())
    return h.hexdigest()


# 确定code注册码
def make_confirm_string(user):
    now = timezone.now()
    code = hash_code(user.username + 'register', str(now))
    ConfirmString.objects.create(code=code, user=user,)
    return code


# 完成发送邮箱的任务-注册用户
def send_email_for_register(email, code):

    subject = '来自黄宇航的毕设项目'

    # 正式消息
    html_content = '''
                    <p>感谢注册<a href="http://{}/accounts/confirm/?code={}" target=blank>www.Masterpaopao.com</a>，\
                    这里是我的毕设项目《基于Python开发的技术交流平台》，邀请你来体验！</p>
                    <p>请点击站点链接完成注册确认！</p>
                    '''.format('127.0.0.1:8000', code,)
    # 备用消息
    text_content = '''感谢注册www.Masterpaopao.com的用户，这里是我的毕设项目《基于Python开发的技术交流平台》，邀请你来体验！\
                    如果你看到这条消息，说明你的邮箱服务器不提供HTML链接功能，请手动复制以下链接访问：
                    http://{}/accounts/confirm/?code={}
                    '''.format('127.0.0.1:8000', code,)

    msg = EmailMultiAlternatives(subject, text_content, settings.EMAIL_HOST_USER, [email])
    msg.attach_alternative(html_content, "text/html")
    msg.send()


# 确定code找回密码
def make_password_string(user):
    now = timezone.now()
    code = hash_code(user.username + 'password', str(now))
    ConfirmString.objects.create(code=code, user_id=user.id,)
    return code


# 完成发送邮箱的任务-找回密码
def send_email_for_find(email, code):

    subject = '来自黄宇航的毕设项目'

    # 正式消息
    html_content = '''
                    <p>找回密码使用这个链接<a href="http://{}/accounts/set_password/?code={}" target=blank>www.Masterpaopao.com</a>，\
                    这里是我的毕设项目《基于Python开发的技术交流平台》，邀请你来体验！</p>
                    <p>请点击站点链接完成找回密码！</p>
                    '''.format('127.0.0.1:8000', code,)
    # 备用消息
    text_content = '''你正在www.Masterpaopao.com上找回密码，这里是我的毕设项目《基于Python开发的技术交流平台》，邀请你来体验！\

bbs/accounts/templates/accounts/confirm.html
{% extends 'bbscopy/base.html' %}
{% load static %}

{% block title %}
UP2U - BBS | 邮箱验证
{% endblock %}

{% block content %}
<div class="col-4 m-auto">
    {% if success_message %}
    <h1 class="h3 mt-5 mb-5 text-success font-weight-normal text-center">{{success_message}}</h1>
    {% else %}
        {% if error_message %}
        <h1 class="h3 mt-5 mb-5 text-danger font-weight-normal text-center">{{error_message}}</h1>
        {% else %}
        <h1 class="h3 mt-5 mb-5 font-weight-normal text-center">您好，来这儿有什么事呢？</h1>
        {% endif %}
    {% endif %}
    <div class="mb-1">
        {% if success_message %}
        <h3 class="mt-3 mb-3 text-success text-center">等待页面自动跳转中...</h3>
        {% endif %}
        <a class="btn btn-lg btn-primary btn-block mt-5" href="{% url 'accounts:login_user'%}" target="_blank">登录</a>
    </div>
    <p class="mt-5 mb-3 text-muted text-center">&copy; Masterpaopao</p>
</div>

{% if success_message %}
<script>
        window.setTimeout("window.location='/accounts/login/'",2000);
</script>
{% endif %}

{% endblock %}

bbs/accounts/templates/accounts/find_password.html
{% extends 'bbscopy/base.html' %}
{% load static %}

{% block title %}
UP2U - BBS | 找回密码
{% endblock %}


{% block content %}
<div class="col-4 m-auto">
    <form class="form-signin mt-5" action="{% url 'accounts:find_password' %}" method="POST">
        {% csrf_token %}
        {% if error_message %}
        <h1 class="h3 mt-5 mb-5 text-danger font-weight-normal text-center">{{error_message}}</h1>
        {% else %}
        <h1 class="h3 mt-5 mb-5 font-weight-normal text-center">找回密码</h1>
        {% endif %}
        <label for="inputName">用户名：</label>
        <input type="text" id="inputName" name="inputName" class="form-control mb-3" placeholder="您的用户名是..."
            required autofocus>
        <label for="inputEmail">邮箱：</label>
        <input type="text" id="inputEmail" name="inputEmail" class="form-control mb-3"
            placeholder="您的绑定邮箱是..." required>
        <div class="mb-3">
            <a class="float-right" href="{% url 'accounts:login_user' %}">返回登录</a>
        </div>
        <button class="btn btn-lg btn-primary btn-block mt-5" type="submit">校验</button>
        <p class="mt-5 mb-3 text-muted text-center">&copy; Masterpaopao</p>
    </form>
</div>
{% endblock %}

bbs/accounts/templates/accounts/login.html
{% extends 'bbscopy/base.html' %}
{% load static %}

{% block title %}
UP2U - BBS | 用户登录
{% endblock %}


{% block content %}
<div class="col-4 m-auto">
    <form class="form-signin mt-5" action="{% url 'accounts:login_user' %}" method="POST">
        {% csrf_token %}
        {% if success_message %}
        <h1 class="h3 mt-5 mb-5 text-success font-weight-normal text-center">{{success_message}}</h1>
        {% else %}
            {% if error_message %}
            <h1 class="h3 mt-5 mb-5 text-danger font-weight-normal text-center">{{error_message}}</h1>
            {% else %}
            <h1 class="h3 mt-5 mb-5 font-weight-normal text-center">旧人，欢迎您</h1>
            {% endif %}
        {% endif %}
        <label for="inputName">用户：</label>
        <input type="text" id="inputName" name="inputName" class="form-control mb-3" placeholder="您的名字..."
            required autofocus>
        <label for="inputPassword">密码：</label>
        <input type="password" id="inputPassword" name="inputPassword" class="form-control mb-3"
            placeholder="您的密码..." required>
        <div class="checkbox mb-3">
            <label>
                <input checked type="checkbox" value="remember-me"> 记住我
            </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">登录</button>
        <div class="mt-1">
            <a class="float-left"  href="{% url 'accounts:find_password'%}">忘记密码？</a>
            <a class="float-right" href="{% url 'accounts:register_user'%}">没有帐号？立即注册</a>
        </div>
        <p class="mt-5 mb-3 text-muted text-center">&copy; Masterpaopao</p>
    </form>
</div>
{% endblock %}

bbs/accounts/templates/accounts/personal.html
{% extends 'bbscopy/base.html' %}
{% load static %}

{% block title %}
UP2U - BBS | 个人中心
{% endblock %}

{% block content %}

<div class="container mt-5 mb-5">

    <div class="row">
        <!-- left -->
        <div class="col-lg-4 col-xlg-3 col-md-5">
            <div class="card">
                <div class="card-header bg-white">
                    <span class="text-info">个人信息</span>
                </div>
                <div class="card-body">
                    <div class="m-t-30 text-center">
                        {% if now_user_d.picture %}
                        <img src="{{ now_user_d.picture.url }}" class="img-circle" height="150" width="150">
                        {% else %}
                        <img src="{% static 'images/公用头像.jpg' %}" class="img-circle" height="150" width="150">
                        {% endif %}
                        <h4 class="card-title m-t-10 mt-3 text-dark">{{now_user.user}}</h4>
                        <div class="row text-center justify-content-md-center">
                            <div class="col-4 flex-column">
                                <div class="font-medium">发帖</div>
                                <div class="font-medium">{{now_user_q.count}}</div>
                            </div>
                            <div class="col-4 flex-column">
                                <div class="font-medium">评论</div>
                                <div class="font-medium">{{now_user_c.count}}</div>
                            </div>
                        </div>
                    </div>
                </div>
                <hr>
                <div class="card-body">
                    <form action="{% url 'accounts:personal' %}" method="post" enctype="multipart/form-data" novalidate>
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="personal_name">昵称:</label>
                            <input type="text" name="ersonal_name" id="personal_name" value="{{now_user.user}}"
                                disabled>
                        </div>
                        <div class="form-group">
                            <label for="personal_email">邮箱:</label>
                            <input type="email" name="personal_email" id="personal_email"
                                value="{{now_user.user.email}}" disabled>
                        </div>
                        <div class="form-group">
                            <label for="personal_sex">性别:</label>
                            <input class="ml-1 mr-1" {% if now_user_d.sex == '1' %} checked {% endif %} type="radio"
                                name="personal_sex" id="personal_sex_b" value="1">男
                            <input class="ml-1 mr-1" {% if now_user_d.sex == '2' %} checked {% endif %} type="radio"
                                name="personal_sex" id="personal_sex_g" value="2">女
                        </div>
                        <div class="form-group">
                            <label for="personal_country">国家:</label>
                            <input type="text" name="personal_country" id="personal_country"
                                value="{{now_user_d.country}}">
                        </div>
                        <div class="form-group">
                            <label for="personal_picture">头像:</label>
                            <input type="file" name="personal_picture" id="personal_picture">
                        </div>
                        <input class="btn btn-light mt-2 ml-5" type="submit" value="更新">
                        <input class="btn btn-light mt-2 ml-5" type="reset" value="重置">
                    </form>
                </div>
            </div>

            <div class="card mt-5">
                <div class="card-header bg-white">
                    <span class="text-info">发帖历史</span>
                </div>
                <div class="card-body">
                    {% if now_user_q %}
                        {% for q in now_user_q %}
                        <p><a href="{% url 'bbscopy:detail' q.id%}" class="text-dark">{{q.question_title}}</a></p> 
                        {% endfor %}
                    {% else %}
                        <p class="text-dark">此用户还未发过贴~</p>
                    {% endif %}
                </div>
            </div>
        </div>

        <!-- right -->
        <div class="col-lg-8 col-xlg-9 col-md-7">
            <div class="card">
                <!-- Nav tabs -->
                <ul class="nav nav-tabs profile-tab" role="tablist">
                    <li class="nav-item"> <a class="nav-link" data-toggle="tab" href="#!" role="tab"
                            aria-expanded="true">回帖列表</a> </li>
                </ul>
                <!-- Tab panes -->
                <div class="tab-content">
                    <!-- first tab -->
                    <div class="tab-pane active" id="home" role="tabpanel" aria-expanded="true">
                        <div class="card-body">
                            {% if now_user_c %}
                            <div class="profiletimeline">
                                {% for c in now_user_c %}
                                <div class="sl-item">
                                    <div class="sl-right">
                                        <div>
                                            <p class="m-t-10">{{c.choice_text}}</p>
                                        </div>
                                        <div class="like-comm m-t-20">
                                            <span class="text-dark">原帖：</span>
                                            {% for cc,dd in c_to_d_dict.items %}
                                            {% if c.id == cc %}
                                            <a href="{% url 'bbscopy:detail' c.question_id%}"
                                                class="link m-r-10">{{dd}}</a>
                                            {% endif %}
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                                <hr>
                                {% endfor %}
                            </div>
                            {% else %}
                            <p class="text-dark">此用户还未回过贴~</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

bbs/accounts/templates/accounts/prompt.html
{% extends 'bbscopy/base.html' %}
{% load static %}

{% block title %}
UP2U - BBS | 邮箱跳转
{% endblock %}

{% block content %}
<div class="col-4 m-auto">
    {% if success_message %}
    <h1 class="h3 mt-5 mb-5 text-success font-weight-normal text-center">{{success_message}}</h1>
    {% else %}
    <h1 class="h3 mt-5 mb-5 font-weight-normal text-center">您好，来这儿有什么事呢？</h1>
    {% endif %}
    <div class="mb-1">
        <h3>我还未验证邮箱</h3>
        <a class="btn btn-lg btn-primary btn-block mb-5" href="https://mail.qq.com" target="_blank">前往邮箱</a>
    </div>
    <div class="mb-1">
        <h3>我已验证邮箱</h3>
        <a class="btn btn-lg btn-primary btn-block mb-5" href="{% url 'accounts:login_user'%}" target="_blank">登录</a>
    </div>
    <p class="mt-5 mb-3 text-muted text-center">&copy; Masterpaopao</p>
</div>
{% endblock %}

bbs/accounts/templates/accounts/register.html
{% extends 'bbscopy/base.html' %}
{% load static %}

{% block title %}
UP2U - BBS | 用户注册
{% endblock %}


{% block content %}
<div class="col-4 m-auto">
    <form class="form-signin mt-5" action="{% url 'accounts:register_user' %}" method="POST">
        {% csrf_token %}
        {% if error_message %}
        <h1 class="h3 mt-5 mb-5 text-danger font-weight-normal text-center">{{error_message}}</h1>
        {% else %}
        <h1 class="h3 mt-5 mb-5 font-weight-normal text-center">新人，欢迎您</h1>
        {% endif %}
        {{ registerform.as_p }}
        <div class="checkbox mb-2">
            <label>
                <input checked type="checkbox" value="agree-me">阅读并接受《用户协议》及《隐私权保护声明》
            </label>
        </div>
        <div class="mb-1">
            <a class="float-right" href="{% url 'accounts:login_user' %}">已有账号？直接登录</a>
        </div>
        <button class="btn btn-lg btn-primary btn-block mt-5" type="submit">注册</button>
        <p class="mt-5 mb-3 text-muted text-center">&copy; Masterpaopao</p>
    </form>
</div>
{% endblock %}

bbs/accounts/templates/accounts/set_password.html
{% extends 'bbscopy/base.html' %}
{% load static %}

{% block title %}
UP2U - BBS | 设置新密码
{% endblock %}


{% block content %}
<div class="col-4 m-auto">
    {% if success_message %}
    <h1 class="h3 mt-5 mb-5 text-success font-weight-normal text-center">{{success_message}}</h1>
    {% else %}
        {% if error_message %}
        <h1 class="h3 mt-5 mb-5 text-danger font-weight-normal text-center">{{error_message}}</h1>
        {% else %}
        <h1 class="h3 mt-5 mb-5 font-weight-normal text-center">您好，来这儿有什么事呢？</h1>
        {% endif %}
    {% endif %}
    <form class="form-signin mt-5" action="{% url 'accounts:set_password' %}" method="POST">
        {% csrf_token %}
        <label for="inputName">用户名：</label>
        <input type="text" id="inputName" name="inputName" class="form-control mb-3" value="{{username}}"
            required autofocus>
        <label for="inputPassword1">新密码：</label>
        <input type="password" id="inputPassword1" name="inputPassword1" class="form-control mb-3" placeholder="您的新密码是..."
        minlength="6" maxlength="18" required autofocus>
        <label for="inputPassword2">再次输入新密码：</label>
        <input type="password" id="inputPassword2" name="inputPassword2" class="form-control mb-3"
        minlength="6" maxlength="18" placeholder="再次输入您的新密码..." required>
        <button class="btn btn-lg btn-primary btn-block mt-5" type="submit">设置</button>
    </form>
    <p class="mt-5 mb-3 text-muted text-center">&copy; Masterpaopao</p>
</div>

{% if success_status %}
<script>
        window.setTimeout("window.location='/accounts/login/'",2000);
</script>
{% endif %}


{% endblock %}