bbs/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('personal/',views.personal,name='personal'),
    path('confirm/',views.confirm,name='confirm'),
    path('prompt/',views.prompt,name='prompt'),
    path('login/', views.login_user, name="login_user"),
    path('logout/',views.logout_user, name='logout_user'),
    path('register/',views.register_user, name='register_user'),
    path('find_password/', views.find_password, name='find_password'),
    path('set_password/', views.set_password, name='set_password')
]

bbs/bbscopy/urls.py
from django.urls import path
from . import views

app_name = "bbscopy"
urlpatterns = [
    # path('', views.QuestionListView.as_view(), name='index'),
    path('', views.index, name='index'),
    # path('topic/', views.TopicCreateView.as_view(), name='topic'),
    path('topic/', views.topic, name='topic'),
    path('reply/<int:bbscopy_id>/', views.reply, name='reply'),
    path('detail/<int:bbscopy_id>/', views.detail, name='detail'),
]

bbs/up2u_bbs/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('bbscopy/', include('bbscopy.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

bbs/bbscopy/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.html import mark_safe
from markdown import markdown

class Question(models.Model):
    class Meta:
        verbose_name = '主题'
        verbose_name_plural = '主题'
    
    user = models.ForeignKey(User,on_delete=models.CASCADE,default=1,verbose_name='作者')
    question_title = models.CharField(max_length=40,verbose_name='标题')
    question_text = models.TextField(max_length=9999,default="",verbose_name='内容')
    pub_date = models.DateTimeField(auto_now_add=True,verbose_name='时间')
    picture = models.FileField(blank=True,null=True)
    def __str__(self):
        return str(self.user) +":"+ self.question_title

    def get_text_to_md(self):
        return mark_safe(markdown(self.question_text))


class Choice(models.Model):
    class Meta:
        verbose_name = '评论'
        verbose_name_plural = '评论'
    
    choice_text = models.CharField(max_length=200,verbose_name='评论')
    user = models.ForeignKey(User,on_delete=models.CASCADE,default=1,verbose_name='作者')
    question = models.ForeignKey(Question, on_delete=models.CASCADE,verbose_name='主题')
    picture = models.FileField(blank=True,null=True)
    def __str__(self):
        return str(self.user)+":"+ self.choice_text
    
    def get_text_to_md(self):
        return mark_safe(markdown(self.choice_text))
    

bbs/bbscopy/forms.py
from django import forms
from .models import Question,Choice

class ChoiceForm(forms.ModelForm):
    choice_text = forms.CharField(
        label = "发表评论",
        widget = forms.Textarea(
            attrs={
                'rows':'3',
                'cols':'30',
                'class':'form-control',
                'placeholder':'不超过150字...'
            }
        )
    )
    picture = forms.FileField(
        label = "上传图片(可选)",
        required = False,
        widget = forms.FileInput(
            attrs={
                'class':'form-control',
            }
        )
    )
    class Meta:
        model = Choice
        fields = ['choice_text','picture']


class QuestionForm(forms.ModelForm):
    question_title = forms.CharField(
        label = "帖子标题",
        widget = forms.TextInput(
            attrs={
                'class':'form-control',
                'style':'width:500px;',
                'placeholder':'不超过20字...',
                'minlength':'2',
                'maxlength':'20'
            }
        )
    )
    question_text = forms.CharField(
        label = "帖子内容",
        required = False,
        widget = forms.Textarea(
            attrs={
                'rows':'3',
                'cols':'30',
                'class':'form-control',
                'placeholder':'请尽情畅所欲言...'
            }
        )
    )
    picture = forms.FileField(
        label = "上传图片(可选)",
        required = False,
        widget = forms.FileInput(
            attrs={
                'class':'form-control',
            }
        )
    )
    class Meta:
        model = Question
        fields = ['question_title','question_text','picture']

bbs/bbscopy/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.urls import reverse

from .models import Question,Choice
from accounts.models import UserUpdate
from .forms import QuestionForm
from .forms import ChoiceForm
from django.db.models import Q

from django.contrib.auth.decorators import login_required
from django.views.generic import ListView,CreateView


# 论坛首页
def index(request):
    latest_bbscopy_list = Question.objects.order_by('-pub_date')
    
    query = request.GET.get('query')
    if query:
        latest_bbscopy_list = latest_bbscopy_list.filter(
            Q(question_title__icontains=query) | 
            Q(user__username__icontains=query) |
            Q(pub_date__icontains=query)
        ).distinct()

    questionform = QuestionForm()
    return render(request,'bbscopy/index.html',
    {'latest_bbscopy_list':latest_bbscopy_list,'questionform':questionform,'now_user':{'user':request.user,'is_login':request.user.is_authenticated},})


# 帖子详情
def detail(request,bbscopy_id):
    try:
        bbscopy = Question.objects.get(pk=bbscopy_id)
        choiceform = ChoiceForm()
        # 帖子作者的头像
        q_pic = UserUpdate.objects.get(user_id=bbscopy.user_id).picture
        # 评论人的头像
        u_pic_list = UserUpdate.objects.all()
        u_choice_list = bbscopy.choice_set.all()
        u_to_p_dict = {}
        for u in u_choice_list:
            u_to_p_dict[u.user_id] = u_pic_list.get(user_id=u.user_id).picture
            
    except Question.DoesNotExist:
        raise Http404("这个帖子的id不存在！")
    return render(request, 'bbscopy/detail.html', 
    {'q_pic':q_pic,'u_to_p_dict':u_to_p_dict,'bbscopy': bbscopy,'choiceform':choiceform,
    'now_user':{'user':request.user,'is_login':request.user.is_authenticated}})


# 发表帖子
@login_required
def topic(request):
    try:
        if request.method == 'POST':
            form = QuestionForm(request.POST,request.FILES or None)
            if form.is_valid():
                topic = form.save(commit=False)
                topic.user = request.user
                topic.save()

    except (KeyError):
        return render(request, 'bbscopy/index.html', {
            'error_message': "页面出错！",
        })

    else:
        return HttpResponseRedirect(reverse('bbscopy:index'))


# 回复帖子
@login_required
def reply(request, bbscopy_id):
    bbscopy = get_object_or_404(Question, pk=bbscopy_id)
    try:
        if request.method == 'POST':
            form = ChoiceForm(request.POST,request.FILES or None)
            # 判断表单是否成功获取
            if form.is_valid():
                # 先不向数据库commit，后面还需绑定问题模型
                reply = form.save(commit=False)
                # 将reply获取到的回复，与问题模型绑定
                reply.question = bbscopy
                # 保险代码，将user给锁定当前登陆的昵称
                reply.user = request.user
                # 保存到数据库
                reply.save()

    except (KeyError):
        return render(request, 'bbscopy/detail.html', {
            'bbscopy': bbscopy,
            'error_message': "页面出错！",
        })

    else:
        return HttpResponseRedirect(reverse('bbscopy:detail', args=(bbscopy.id,)))


class QuestionListView(ListView):
    model = Question
    context_object_name = 'latest_bbscopy_list'
    template_name = 'bbscopy/index.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['now_user'] = {'user':self.request.user,'is_login':self.request.user.is_authenticated}
        context['questionform'] = QuestionForm()
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        query = self.request.GET.get('query')
        if query:
            return queryset.filter(
                Q(question_title__icontains=query) | 
                Q(user__username__icontains=query) |
                Q(pub_date__icontains=query)
            ).distinct()
        return queryset


class TopicCreateView(CreateView):
    model = Question
    template_name = 'bbscopy/index.html'
    fields = ('question_title','question_text','picture')

    def form_valid(self,form):
        question = form.save(commit=False)
        question.author = self.request.user
        question.save()
        return HttpResponseRedirect(reverse('bbscopy:index'))

bbs/bbscopy/templates/bbscopy/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'cdn/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/offcanvas.css'%}" >
    {% block csslink %}
    {% endblock %}
</head>
<body>
 
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <span class="text-white h5 mt-2 mr-2">UP2U - BBS</span>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample07" aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample07">
        <ul class="navbar-nav ml-3 mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/bbs">首页<span class="sr-only">(current)</span></a>
          </li>
        </ul>
        <form class="form-inline my-2 my-md-0" method="GET" action="{% url 'bbscopy:index' %}">
          <input class="form-control" type="text" placeholder="关键词..." aria-label="Search" 
          name="query" value="{{request.GET.query}}">
        </form>
            {% if now_user.is_login %}
            <a class="nav-link ml-5 text-light" href="#!">{{now_user.user}}</a>
            <a class="nav-link" href="{% url 'accounts:personal' %}">个人中心</a>
            <a class="nav-link text-info" href="{% url 'accounts:logout_user' %}">登出</a>
            {% else %}
            <a class="nav-link ml-5" href="{% url 'accounts:login_user' %}">登录</a>
            <a class="nav-link" href="{% url 'accounts:register_user' %}">注册</a>
            {% endif %}
      </div>
    </div>
</nav>


{% block nav-second %}
{% endblock %}

{% block content %}
{% endblock %}
   

<script src="{% static 'cdn/bootstrap.min.js'%}"></script>
<script src="{% static 'cdn/jquery.slim.min.js'%}"></script>
<script src="{% static 'cdn/popper.min.js'%}"></script>

{% block jslink %}
{% endblock %}

</body>
</html>

bbs/bbscopy/templates/bbscopy/detail.html
{% extends 'bbscopy/base.html'%}
{% load static %}

{% block title %}
UP2U - BBS | {{bbscopy.question_title}}
{% endblock %}

{% block csslink %}
<link rel="stylesheet" href="{% static 'editor.md/css/editormd.min.css' %}" />
{% endblock %}

<h1>{{error_message}}</h1>

{% block nav-second %}
<div class="nav-scroller bg-light box-shadow">
    <nav class="nav nav-underline container">
        <span class="text-danger mt-2">热门评论：</span>
        {% for one in bbscopy.choice_set.all %}
        {% if 3 >= forloop.counter %}
        <span class="text-dark mt-2">{{one.choice_text}}</span>
        <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
        {% endif %}
        {% endfor %}
    </nav>
</div>

{% endblock %}


{% block content %}
<div class="container card flex-md-row mt-3 box-shadow border-white">
    <!-- 左边帖子主题部分 -->
    <div class="card-body d-flex flex-column align-items-start">
        <strong class="d-inline-block text-primary">UP2U - BBS</strong>
        <h3 class="mt-2">
            <a class="text-dark" href="">{{bbscopy.question_title}}</a>
        </h3>
        <div class="mt-2 text-muted">{{bbscopy.pub_date | date:"Y/m/d H:i:s"}}</div>
        <p class="card-text mt-2">楼主：{{bbscopy.user}}</p>
    </div>
    <!-- 右边作者信息 -->
    <div class="card-body little-profile text-center border-left">
        <div class="pro-img">
            <img width="70" height="70" style="border-radius: 50%;" src="{{q_pic.url}}" alt="{{bbscopy.user}}">
        </div>
        <h3 class="m-b-0 mt-1">{{bbscopy.user}}</h3>
        <button type="button" class="btn btn-primary btn-sm">关注</button>
    </div>
</div>

{% if bbscopy.question_text or bbscopy.picture %}
<div class="container card mt-3 box-shadow border-white">
    <h4 class="card-title border-bottom border-secondary mt-3 mb-3 pb-1">帖子内容</h4>
    <div class="comment-widgets m-b-20">
        <figure class="figure col-10">
            <figcaption class="text-dark h6 ml-3">{{bbscopy.get_text_to_md}}</figcaption>
            {% if bbscopy.picture %}
            <img src="{{bbscopy.picture.url}}" class="mt-1 ml-3 figure-img img-fluid rounded "
            alt="{{bbscopy.user}}的帖子图片" style="max-width: 800px;max-height: 400px;">
            {% endif %}
        </figure>
    </div>
</div>
{% endif %}

<div class="container card-body mt-3 box-shadow">
    <h4 class="card-title">最新评论</h4>
    <h6 class="card-subtitle border-bottom border-secondary mb-3 pb-1">回帖根据评论时间升序排列</h6>
    {% if bbscopy.choice_set.all %}
    <div class="comment-widgets m-b-20">
        {% for c in bbscopy.choice_set.all %}
        <div class="d-flex flex-row">
            <div class="p-2">
                {% for u,p in u_to_p_dict.items %}
                    {%  if c.user_id == u%}
                    <img style="border-radius: 50%;" src="{{ p.url }} " alt="{{c.user}}" height="50" width="50">
                    {% endif %}
                {% endfor %}
            </div>
            <div class="comment-text w-100 ml-3">
                <h5 class=" mt-3 mb-0">{{c.user}}</h5>
                <div class="comment-footer mb-2">
                    <span class="count text-dark small">{{forloop.counter}}楼</span>
                </div>
                <div class="m-b-5 m-t-10 border-bottom-0 pb-3">
                    {{c.get_text_to_md}}
                    {% if c.picture %}
                    <div class="mt-1">
                        <img src="{{ c.picture.url }}" alt="{{c.user}}的图片" style="max-width: 800px;max-height: 400px;">
                    </div>
                    {% endif %}
                </div>

            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <p>此帖子还没有评论呢~</p>
    {% endif %}
</div>

<div class="container card p-0 mt-3 mb-3 box-shadow border-white">
    <div class="card-header bg-white">想说点什么……</div>
    <div class="card-body p-2 mt-2 ml-2">
        {% if now_user.is_login %}
        <blockquote class="blockquote">
            <form action="{%url 'bbscopy:reply' bbscopy.id %}" method="POST" enctype="multipart/form-data" novalidate>
                {% csrf_token %}
                <div class="form-group">
                    <label for="reply_name">昵称:
                        <input disabled type="text" class="form-control" id="reply_name" name="reply_name"
                            value="{{now_user.user}}"></label>
                </div>
                <div class="form-group" style="height:500px;">
                    <label for="choice_text">发表评论:</label>
                    <div id="editor">
                            {{ choiceform.choice_text }}</div>
                </div>
                <div class="form-group mt-5">
                    <label for="picture">上传图片(可选):
                    {{ choiceform.picture }}</label>
                </div>
                <input class="btn btn-light btn-lg mt-2" type="submit" value="提交">
            </form>
        </blockquote>
        {% else %}
        <h3>快去登录你的帐号来发表点看法吧~</h3>
        <a class="btn btn-primary col-1 mb-3" href="{% url 'accounts:login_user' %}" role="button">登录</a>
        {% endif %}
        <footer class="mt-3 blockquote-footer p-0"><cite title="Source Title">感谢你对论坛社区做出的贡献~ </cite></footer>
    </div>
</div>

{% endblock %}


{% block jslink %}
<script src="{% static 'editor.md/examples/js/jquery.min.js' %}"></script>
<script src="{% static 'editor.md/editormd.min.js' %}"></script>
<script type="text/javascript">
    $(function() {
        var editor = editormd("editor", {
            width: "100%",
            height: "100%",
            markdown: "请输入你的评论...",     
            path : "{% static 'editor.md/lib/' %}"
        });
    });
</script>
{% endblock %}

bbs/bbscopy/templates/bbscopy/index.html
{% extends 'bbscopy/base.html'%}
{% load static %}

{% block title %}
    UP2U - BBS
{% endblock %}

{% block csslink %}
<link rel="stylesheet" href="{% static 'editor.md/css/editormd.min.css' %}" />
{% endblock %}


<h1>{{error_message}}</h1>

{% block nav-second %}

<div class="nav-scroller bg-light box-shadow">
    <nav class="nav nav-underline container align-items-baseline">
        <span class="text-danger mt-2">热门话题：</span>
        {% for one in latest_bbscopy_list %}
            {% if one.choice_set.count >= 3 %}
                <a  class="nav-link" href="{% url 'bbscopy:detail' one.id %}">
                {{ one.question_title}}
                <span class="badge badge-pill bg-warning align-text-bottom">
                {{one.choice_set.count}}</span>
            {% endif %}
        {% endfor %}
      </a>
    </nav>
  </div>
{% endblock %}


{% block content %}
<div class="container mt-3 mb-3 p-0 box-shadow">
    {% if latest_bbscopy_list %}  
    <table class="table table-striped table-light table-bordered">
        <tr class="table-primary">
            <th style="text-align: center;">帖子主题</th>
            <th style="text-align: center;">帖子作者</th>
            <th style="text-align: center;">发布日期</th>
            <th style="text-align: center;">总评论数</th>
            <th style="text-align: center;">最新评论</th>
        </tr>
        {% for bbscopy in latest_bbscopy_list %}
        <tr>
            <td style="text-align: center;"><a href="{% url 'bbscopy:detail' bbscopy.id %}">{{ bbscopy.question_title }}</a></td>
            <td style="text-align: center;">{{bbscopy.user}}</td>
            <td style="text-align: center;">{{bbscopy.pub_date | date:"Y/m/d H:i"}}</td>
            <td style="text-align: center;">{{bbscopy.choice_set.count}}</td>
            {% if bbscopy.choice_set.last.choice_text %}
            <td style="text-align: center;">{{bbscopy.choice_set.last.choice_text | slice:":5" }}……</td>
            {% else %}
            <td style="text-align: center;font-style:italic;">快来抢沙发</td>
            {% endif %}   
        </tr>
        {% endfor %}
    </table>
    {% else %}
    <p>No bbscopy are available.</p>
    {% endif %}
</div>

<div class="container card p-0 mt-3 mb-3 box-shadow border-white">
        <div class="card-header bg-white card-title">请发个帖子……</div>
        <div class="card-body p-2 mt-2 ml-2">
            {% if now_user.is_login %}
            <blockquote class="blockquote">
                <form action="{% url 'bbscopy:topic' %}" method="POST" enctype="multipart/form-data" novalidate>
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="topic_user">昵称:
                            <input disabled type="text" class="form-control" 
                            id="topic_user" name="topic_user" value="{{now_user.user}}"></label>
                    </div>
                    <div class="form-group">
                        <label for="question_title">帖子标题:
                        {{ questionform.question_title }}</label>
                    </div>
                    <div class="form-group" style="height:500px;">
                        <label for="question_text">帖子内容:</label>
                        <div id="editor">
                                {{ questionform.question_text }}</div>
                    </div>
                    <div class="form-group mt-5">
                        <label for="picture">上传图片(可选):
                        {{ questionform.picture }}</label>
                    </div>
                    <input class="btn btn-light btn-lg mt-3" type="submit" value="发布">
                </form>
            </blockquote>
            {% else %}
            <h3>快去登录你的帐号来发布个帖子吧~</h3>
            <a class="btn btn-primary col-1 mb-3" href="{% url 'accounts:login_user' %}" role="button">登录</a>
            {% endif %}
            <footer class="mt-3 blockquote-footer p-0"><cite title="Source Title">感谢你对论坛社区做出的贡献~ </cite></footer>
        </div>
    </div>
{% endblock %}

{% block jslink %}
<script src="{% static 'editor.md/examples/js/jquery.min.js' %}"></script>
<script src="{% static 'editor.md/editormd.min.js' %}"></script>
<script type="text/javascript">
    $(function() {
        var editor = editormd("editor", {
            width: "100%",
            height: "100%",
            markdown: "请输入你的帖子内容...",     
            path : "{% static 'editor.md/lib/' %}"
        });
    });
</script>
{% endblock %}